[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "mad still zoo control industry cause dumb transfer chief catalog renew first neither supreme chef convince half consider place fold myself position east rebuild"
